# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Update Blog

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: test
      run: git config -l
    
    - name: Checkout with Git LFS
      uses: actions/checkout@v2
      
    
    - name: dep
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
        
    - run: npm install --global yarn
    - run: cd ../../
    - run: yarn install
    - run: set -e
    - run: yarn build
    
    - run: mv docs/.vuepress/dist ~/dist

    - run: echo blog.joklr.org > CNAME
    - run: git init
    
    - run: git config --local user.email "github-actions[bot]@users.noreply.github.com"
    - run: git config --local user.name "github-actions[bot]"

    - run: git add .
    - run: git commit -m "Add changes"
    - run: git config --local --unset-all "http.https://github.com/.extraheader"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
