name: Update Blog

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: test
      run: git config -l
    
    - name: Checkout with Git LFS
      uses: actions/checkout@v2
      
    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}- 
    
    - name: import nodejs
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
    
#     - name: install dependencies
#       run: npm install --global yarn
#     - run: cd ../../
#     - run: yarn install
    
    - name: build page
      run: yarn build
    - run: rm -rf ./docs
    - run: mv post/.vuepress/dist ./docs
    - run: echo "blog.Joklr.org" > ./docs/CNAME
    
    - name: git repo init
      run: git config --local user.email "github-actions[bot]@users.noreply.github.com"
    - run: git config --local user.name "github-actions[bot]"
    - run: git add .
    - run: git commit -m "Add changes"
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
